# Header optionally contains the timestamp of the clicked image
std_msgs/Header header

# Image topic on which the clicked image was published
string image_topic_name

# Coordinates of the clicked point
uint32 x
uint32 y

# Create or update a transform corresponding to the clicked point from the base frame to `clicked_frame_id`
string clicked_frame_id

# If True, save the resulting transform from the clicked point normal calculation as a persistent transform in the Agent.
# Defaults to True to preserve previous behavior.
# TODO(7024): Delete this flag once all Quick Tasks are updated to not depend on setting the transform as a side effect of clicking.
bool save_transform true
---
bool success

# Transform from the base frame to the frame set in the `clicked_frame_id` field
geometry_msgs/TransformStamped point_normal
