# Service to retrieve a joint state from the Parameter Manager

bool has_timeout
builtin_interfaces/Duration timeout

---

bool success
sensor_msgs/JointState joint_state
sensor_msgs/MultiDOFJointState multi_dof_joint_state
