# Service which retrieves MTC solutions based on MTC task ID for debugging.
# The response will contain solutions only if the status indicates the request was handled successfully.
string task_id
---
moveit_studio_sdk_msgs/RequestStatus status
MtcSolution[] solutions
