# Interface for configuring a velocity/force controller.
# The configuration service will first load the configuration from the parameter server, and then override the fields
# that are present in this request.
# An empty request will reset the configuration to the default values (or those present in the parameter server).

# Cartesian velocity and acceleration limits.
bool set_cartesian_velocity_limits
geometry_msgs/Twist cartesian_velocity_limits

bool set_cartesian_acceleration_limits
geometry_msgs/Accel cartesian_acceleration_limits

# Joint velocity and acceleration limits.
bool set_joint_velocity_limits
float64[] joint_velocity_limits

bool set_joint_acceleration_limits
float64[] joint_acceleration_limits

---
# True if the configuration was successfully set.
bool success

# Error message if success is false.
string error_message
