# goal

string objective_name

# Default values of named parameters in the predefined objective will be overridden by the values provided in `parameter_overrides` below.
moveit_pro_sdk_msgs/BehaviorParameter[] parameter_overrides
---
# result
moveit_msgs/MoveItErrorCodes error_code
string error_message
---
#feedback (empty)
