# Describes an action to start teleoperation in MoveIt Studio.

## GOAL

# If true, enables the UI to bring up a user interaction panel to mark teleoperation successful or failed.
bool enable_user_interaction

# (Optional) Prompt to display if user interaction is enabled.
string user_interaction_prompt

# (Optional) Specifies the initial teleoperation mode to start in.
TeleoperationMode initial_mode

---

## FEEDBACK

# The current teleoperation mode
TeleoperationMode current_mode

---

## RESULT

# Whether the teleoperate action completed successfully.
bool success

# (Optional) Free-form string to describe the result.
string reason
