name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_docker:
    name: Docker build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: clang, cxx: clang++ }
          - { cc: gcc, cxx: g++ }
    steps:
      - name: Build Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ghcr.io/picknikrobotics/moveit-studio-sdk
          build-args: |
            CC=${{ matrix.compiler.cc }}
            CXX=${{ matrix.compiler.cxx }}
